-- V1__insert_100_products.sql
-- Script para inserir 100 produtos para o e-commerce

INSERT INTO products (name, description, price, stock, category, active, created_at, updated_at) VALUES
-- Eletrônicos (25 produtos)
('Smartphone Galaxy S21', 'Smartphone de última geração com câmera de alta resolução e processador rápido.', 3999.99, 50, 'Eletrônicos', true, NOW(), NOW()),
('iPhone 13 Pro Max', 'Smartphone premium com sistema iOS, câmera profissional e processador potente.', 6499.99, 35, 'Eletrônicos', true, NOW(), NOW()),
('Smart TV 55" 4K', 'Smart TV com resolução 4K, sistema operacional integrado e acesso a aplicativos de streaming.', 2799.99, 25, 'Eletrônicos', true, NOW(), NOW()),
('Notebook Gamer Acer', 'Notebook potente com processador i7, 16GB RAM e placa de vídeo dedicada para jogos.', 5299.90, 20, 'Eletrônicos', true, NOW(), NOW()),
('Fone de Ouvido Bluetooth', 'Fone sem fio com cancelamento de ruído e bateria de longa duração.', 299.90, 100, 'Eletrônicos', true, NOW(), NOW()),
('Tablet iPad Air', 'Tablet leve e poderoso com tela de alta resolução e processador A14 Bionic.', 4799.90, 30, 'Eletrônicos', true, NOW(), NOW()),
('Console PlayStation 5', 'Console de videogame de última geração com controle DualSense e SSD ultrarrápido.', 4499.90, 15, 'Eletrônicos', true, NOW(), NOW()),
('Console Xbox Series X', 'Console poderoso da Microsoft com capacidade de jogar em 4K e alta taxa de quadros.', 4299.90, 18, 'Eletrônicos', true, NOW(), NOW()),
('Smartwatch Apple Watch', 'Relógio inteligente com monitoramento de saúde e notificações do smartphone.', 2499.90, 40, 'Eletrônicos', true, NOW(), NOW()),
('Câmera DSLR Canon', 'Câmera profissional com sensor full-frame e capacidade de gravação em 4K.', 5899.90, 12, 'Eletrônicos', true, NOW(), NOW()),
('Caixa de Som Bluetooth JBL', 'Caixa de som portátil à prova d\'água com bateria de longa duração.', 399.90, 80, 'Eletrônicos', true, NOW(), NOW()),
('Monitor Ultrawide 34"', 'Monitor curvo com proporção 21:9 ideal para produtividade e jogos.', 2899.90, 22, 'Eletrônicos', true, NOW(), NOW()),
('Teclado Mecânico Gamer', 'Teclado com switches mecânicos e iluminação RGB personalizável.', 349.90, 65, 'Eletrônicos', true, NOW(), NOW()),
 ('Mouse Gamer', 'Mouse de alta precisão com sensor óptico e botões programáveis.', 199.90, 70, 'Eletrônicos', true, NOW(), NOW()),
 ('Impressora Multifuncional', 'Impressora com scanner e copiadora, conexão Wi-Fi e suporte a impressão frente e verso.', 999.90, 25, 'Eletrônicos', true, NOW(), NOW()),
 ('Roteador Wi-Fi Mesh', 'Sistema de rede mesh para cobertura Wi-Fi em toda a casa sem pontos cegos.', 699.90, 30, 'Eletrônicos', true, NOW(), NOW()),
 ('SSD 1TB', 'Unidade de estado sólido para armazenamento rápido e confiável.', 599.90, 45, 'Eletrônicos', true, NOW(), NOW()),
 ('HDD Externo 4TB', 'Disco rígido externo para backup e armazenamento de arquivos grandes.', 499.90, 35, 'Eletrônicos', true, NOW(), NOW()),
 ('Drone com Câmera 4K', 'Drone com câmera de alta resolução, estabilização e GPS para retorno automático.', 3499.90, 10, 'Eletrônicos', true, NOW(), NOW()),
 ('Projetor Full HD', 'Projetor com resolução 1080p ideal para home cinema.', 2599.90, 15, 'Eletrônicos', true, NOW(), NOW()),
 ('Carregador Sem Fio', 'Carregador por indução compatível com smartphones modernos.', 129.90, 90, 'Eletrônicos', true, NOW(), NOW()),
 ('Power Bank 20000mAh', 'Bateria portátil de alta capacidade para carregar múltiplos dispositivos.', 179.90, 60, 'Eletrônicos', true, NOW(), NOW()),
 ('Leitor de E-books Kindle', 'Leitor de livros digitais com tela antirreflexo e iluminação embutida.', 499.90, 50, 'Eletrônicos', true, NOW(), NOW()),
 ('Webcam Full HD', 'Câmera para videoconferências com resolução 1080p e microfone embutido.', 299.90, 40, 'Eletrônicos', true, NOW(), NOW()),
 ('Adaptador HDMI-USB', 'Conversor para conectar dispositivos HDMI a portas USB-C.', 99.90, 75, 'Eletrônicos', true, NOW(), NOW()),

-- Moda (25 produtos)
 ('Camiseta Básica', 'Camiseta de algodão em diversos tamanhos e cores.', 49.90, 200, 'Moda', true, NOW(), NOW()),
 ('Tênis Esportivo', 'Tênis confortável para corrida e academia.', 199.90, 80, 'Moda', true, NOW(), NOW()),
 ('Jaqueta de Couro', 'Jaqueta estilosa para ocasiões especiais.', 349.90, 30, 'Moda', true, NOW(), NOW()),
 ('Calça Jeans', 'Calça jeans de alta qualidade em diversos modelos.', 139.90, 150, 'Moda', true, NOW(), NOW()),
 ('Vestido de Festa', 'Vestido elegante para ocasiões formais.', 289.90, 40, 'Moda', true, NOW(), NOW()),
 ('Casaco de Inverno', 'Casaco quente e impermeável para dias frios.', 279.90, 50, 'Moda', true, NOW(), NOW()),
 ('Bermuda Casual', 'Bermuda confortável para o dia a dia.', 89.90, 120, 'Moda', true, NOW(), NOW()),
 ('Camisa Social', 'Camisa de tecido nobre para ambiente de trabalho.', 129.90, 80, 'Moda', true, NOW(), NOW()),
 ('Saia Midi', 'Saia elegante de comprimento médio.', 99.90, 60, 'Moda', true, NOW(), NOW()),
 ('Blazer Feminino', 'Blazer sofisticado para looks formais.', 219.90, 45, 'Moda', true, NOW(), NOW()),
 ('Boné Esportivo', 'Boné com proteção UV para atividades ao ar livre.', 59.90, 100, 'Moda', true, NOW(), NOW()),
 ('Sapato Social Masculino', 'Sapato elegante para ocasiões formais.', 249.90, 70, 'Moda', true, NOW(), NOW()),
 ('Sandália Feminina', 'Sandália confortável com salto médio.', 159.90, 85, 'Moda', true, NOW(), NOW()),
 ('Óculos de Sol', 'Óculos estiloso com proteção UV.', 199.90, 75, 'Moda', true, NOW(), NOW()),
 ('Relógio Analógico', 'Relógio elegante com pulseira de couro.', 179.90, 60, 'Moda', true, NOW(), NOW()),
 ('Bolsa Feminina', 'Bolsa espaçosa com múltiplos compartimentos.', 129.90, 65, 'Moda', true, NOW(), NOW()),
 ('Cinto de Couro', 'Cinto durável com fivela metálica.', 69.90, 90, 'Moda', true, NOW(), NOW()),
 ('Meia Esportiva', 'Conjunto com 3 pares de meias para atividades físicas.', 39.90, 150, 'Moda', true, NOW(), NOW()),
 ('Pijama de Algodão', 'Pijama confortável para noites bem dormidas.', 89.90, 80, 'Moda', true, NOW(), NOW()),
 ('Cueca Boxer', 'Kit com 3 cuecas boxers de algodão.', 59.90, 120, 'Moda', true, NOW(), NOW()),
 ('Calcinha de Algodão', 'Kit com 5 calcinhas de algodão.', 49.90, 130, 'Moda', true, NOW(), NOW()),
 ('Sutiã com Bojo', 'Sutiã confortável com bojo e alças ajustáveis.', 69.90, 90, 'Moda', true, NOW(), NOW()),
 ('Gravata de Seda', 'Gravata elegante para ocasiões formais.', 79.90, 60, 'Moda', true, NOW(), NOW()),
 ('Lenço de Seda', 'Lenço versátil para diferentes looks.', 49.90, 70, 'Moda', true, NOW(), NOW()),
 ('Mochila Casual', 'Mochila espaçosa para uso diário.', 129.90, 65, 'Moda', true, NOW(), NOW()),

-- Casa e Decoração (25 produtos)
 ('Jogo de Panelas', 'Conjunto com 5 panelas de alumínio com revestimento antiaderente.', 349.90, 60, 'Casa e Decoração', true, NOW(), NOW()),
 ('Sofá 3 Lugares', 'Sofá confortável para sua sala de estar.', 1299.90, 15, 'Casa e Decoração', true, NOW(), NOW()),
 ('Conjunto de Toalhas', 'Kit com 4 toalhas macias de diferentes tamanhos.', 89.90, 120, 'Casa e Decoração', true, NOW(), NOW()),
 ('Liquidificador', 'Liquidificador potente com múltiplas velocidades.', 129.90, 70, 'Casa e Decoração', true, NOW(), NOW()),
 ('Jogo de Cama Queen', 'Conjunto de lençol, fronha e capa de edredom para cama queen size.', 199.90, 55, 'Casa e Decoração', true, NOW(), NOW()),
 ('Tapete para Sala', 'Tapete macio e durável para sala de estar.', 249.90, 40, 'Casa e Decoração', true, NOW(), NOW()),
 ('Cortina Blackout', 'Cortina que bloqueia a luz solar e proporciona privacidade.', 149.90, 60, 'Casa e Decoração', true, NOW(), NOW()),
 ('Quadro Decorativo', 'Quadro com moldura para decorar ambientes.', 89.90, 80, 'Casa e Decoração', true, NOW(), NOW()),
 ('Vaso de Plantas', 'Vaso elegante para plantas ornamentais.', 59.90, 90, 'Casa e Decoração', true, NOW(), NOW()),
 ('Espelho de Parede', 'Espelho decorativo para ampliar espaços.', 179.90, 45, 'Casa e Decoração', true, NOW(), NOW()),
 ('Mesa de Jantar', 'Mesa robusta para 6 lugares.', 799.90, 25, 'Casa e Decoração', true, NOW(), NOW()),
 ('Cadeira de Escritório', 'Cadeira ergonômica para home office.', 499.90, 35, 'Casa e Decoração', true, NOW(), NOW()),
 ('Luminária de Mesa', 'Luminária moderna com ajuste de intensidade.', 129.90, 70, 'Casa e Decoração', true, NOW(), NOW()),
 ('Conjunto de Talheres', 'Kit com 24 peças de talheres em aço inox.', 149.90, 65, 'Casa e Decoração', true, NOW(), NOW()),
 ('Cesto de Roupa Suja', 'Cesto prático para organizar roupas para lavar.', 69.90, 85, 'Casa e Decoração', true, NOW(), NOW()),
 ('Organizador de Armário', 'Kit com divisórias para organizar gavetas e armários.', 39.90, 100, 'Casa e Decoração', true, NOW(), NOW()),
 ('Jogo de Copos', 'Conjunto com 6 copos de vidro para água e suco.', 49.90, 90, 'Casa e Decoração', true, NOW(), NOW()),
 ('Jogo de Taças', 'Conjunto com 6 taças para vinho.', 79.90, 70, 'Casa e Decoração', true, NOW(), NOW()),
 ('Relógio de Parede', 'Relógio decorativo para ambientes internos.', 69.90, 75, 'Casa e Decoração', true, NOW(), NOW()),
 ('Almofada Decorativa', 'Almofada macia para sofás e camas.', 39.90, 110, 'Casa e Decoração', true, NOW(), NOW()),
 ('Pote Hermético', 'Conjunto com 5 potes para armazenar alimentos.', 59.90, 80, 'Casa e Decoração', true, NOW(), NOW()),
 ('Lixeira Inox', 'Lixeira com pedal e acabamento em aço inox.', 89.90, 65, 'Casa e Decoração', true, NOW(), NOW()),
 ('Persiana Vertical', 'Persiana ajustável para controle de luminosidade.', 199.90, 40, 'Casa e Decoração', true, NOW(), NOW()),
 ('Cabideiro de Chão', 'Cabideiro prático para organizar roupas.', 129.90, 45, 'Casa e Decoração', true, NOW(), NOW()),
 ('Porta-Retrato', 'Porta-retrato elegante para fotos especiais.', 29.90, 110, 'Casa e Decoração', true, NOW(), NOW()),

-- Livros (25 produtos)
 ('Harry Potter: Coleção Completa', 'Box com os 7 livros da saga Harry Potter.', 299.90, 40, 'Livros', true, NOW(), NOW()),
 ('O Poder do Hábito', 'Livro sobre como criar e transformar hábitos.', 59.90, 85, 'Livros', true, NOW(), NOW()),
 ('Dom Casmurro', 'Clássico da literatura brasileira de Machado de Assis.', 39.90, 70, 'Livros', true, NOW(), NOW()),
 ('A Arte da Guerra', 'Livro sobre estratégia e filosofia militar.', 29.90, 90, 'Livros', true, NOW(), NOW()),
 ('Pai Rico, Pai Pobre', 'Livro sobre educação financeira e investimentos.', 49.90, 75, 'Livros', true, NOW(), NOW()),
 ('1984', 'Obra-prima distópica de George Orwell.', 34.90, 60, 'Livros', true, NOW(), NOW()),
 ('Cem Anos de Solidão', 'Obra-prima de Gabriel García Márquez.', 44.90, 50, 'Livros', true, NOW(), NOW()),
 ('O Senhor dos Anéis', 'Trilogia épica de J.R.R. Tolkien.', 129.90, 30, 'Livros', true, NOW(), NOW()),
 ('As Crônicas de Gelo e Fogo', 'Série que inspirou Game of Thrones.', 149.90, 25, 'Livros', true, NOW(), NOW()),
 ('O Pequeno Príncipe', 'Clássico mundial sobre valores essenciais.', 25.90, 100, 'Livros', true, NOW(), NOW()),
 ('A Divina Comédia', 'Obra-prima de Dante Alighieri.', 39.90, 45, 'Livros', true, NOW(), NOW()),
 ('Crime e Castigo', 'Clássico russo de Fiódor Dostoiévski.', 42.90, 40, 'Livros', true, NOW(), NOW()),
 ('A Revolução dos Bichos', 'Fábula política de George Orwell.', 29.90, 65, 'Livros', true, NOW(), NOW()),
 ('O Hobbit', 'Aventura que precede O Senhor dos Anéis.', 39.90, 55, 'Livros', true, NOW(), NOW()),
 ('Orgulho e Preconceito', 'Clássico romance de Jane Austen.', 34.90, 60, 'Livros', true, NOW(), NOW()),
 ('A Menina que Roubava Livros', 'Romance emocionante sobre a Segunda Guerra Mundial.', 44.90, 50, 'Livros', true, NOW(), NOW()),
 ('Sapiens: Uma Breve História da Humanidade', 'Obra de Yuval Harari sobre a história da espécie humana.', 59.90, 70, 'Livros', true, NOW(), NOW()),
 ('O Alquimista', 'Best-seller de Paulo Coelho sobre jornadas pessoais.', 34.90, 75, 'Livros', true, NOW(), NOW()),
 ('A Cabana', 'Romance espiritual de William P. Young.', 29.90, 55, 'Livros', true, NOW(), NOW()),
 ('Anne Frank: O Diário de uma Jovem', 'Relato verídico escrito durante o Holocausto.', 34.90, 60, 'Livros', true, NOW(), NOW()),
 ('Memórias Póstumas de Brás Cubas', 'Clássico de Machado de Assis.', 32.90, 50, 'Livros', true, NOW(), NOW()),
 ('O Cortiço', 'Clássico naturalista brasileiro de Aluísio Azevedo.', 29.90, 65, 'Livros', true, NOW(), NOW()),
 ('Grande Sertão: Veredas', 'Obra-prima de Guimarães Rosa.', 49.90, 40, 'Livros', true, NOW(), NOW()),
 ('Iracema', 'Clássico indianista de José de Alencar.', 24.90, 70, 'Livros', true, NOW(), NOW()),
 ('Vidas Secas', 'Clássico da literatura brasileira de Graciliano Ramos.', 29.90, 60, 'Livros', true, NOW(), NOW());